spring.application.name=filehandler

AWS_S3_BUCKET_NAME=fynd-marketplace-dev--fynd-nice-sync-oms

KEY_TO_PROCESS_BATCH_SIZE=10


ORDER_EXPORT_ROOT_DIRECTORY=OrderExports
ORDER_EXPORT_DATA_DIRECTORY=NewOrders
ORDER_EXPORT_PROCESSED_DIRECTORY=Processed
ORDER_EXPORT_FTP_DIRECTORY=order/exports

ORDER_STATUS_ROOT_DIRECTORY=OrderStatus
ORDER_STATUS_DATA_DIRECTORY=NewOrders
ORDER_STATUS_PROCESSED_DIRECTORY=Processed
ORDER_STATUS_FTP_DIRECTORY=order/status

aws.accessKeyId=your-access-key-id
aws.secretKey=your-secret-access-key
aws.s3.region=ap-south-1



ftp.server=localhost
ftp.port=21
ftp.username=admin
ftp.password=jWBCUw6zEkP3vHgv


FTP_ROOT_DIRECTORY=order
FTP_DATA_DIRECTORY=exports
FTP_PROCESSED_DIRECTORY=processed
S3_UPLOAD_DIRECTORY=ftpcontent
